# Generated by Django 4.2.13 on 2024-08-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('copyright', models.TextField()),
                ('follow_us_content', models.CharField(max_length=300)),
                ('social_address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=300)),
                ('site_url', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, default='info@gmail.com', max_length=200, null=True)),
                ('day_of_week', models.CharField(max_length=100)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('address', models.CharField(max_length=300)),
                ('about_us_content', models.CharField(max_length=300)),
                ('about_us_title', models.CharField(max_length=250)),
                ('service_title', models.CharField(max_length=200)),
                ('service_content', models.CharField(max_length=300)),
                ('site_logo', models.ImageField(upload_to='images/site-setting')),
                ('is_main_setting', models.BooleanField()),
            ],
        ),
    ]
