# Generated by Django 4.2.13 on 2024-08-22 14:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeTableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+989234567891', max_length=128, region='IR')),
                ('email', models.EmailField(max_length=200)),
                ('reserve_date', models.DateTimeField()),
                ('people_count', models.IntegerField(choices=[(1, '1 Person'), (2, '2 People'), (3, '3 People'), (4, '4 People'), (5, '5 or more')], default=1)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('reserve_date', 'name')},
            },
        ),
    ]
