# Generated by Django 4.2.13 on 2024-08-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=350)),
                ('url_title', models.CharField(db_index=True, max_length=350)),
                ('is_active', models.BooleanField(null=True)),
                ('is_delete', models.BooleanField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_module.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url_title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images/products')),
                ('short_description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(null=True)),
                ('is_delete', models.BooleanField(null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_menu', to='menu_module.menu')),
            ],
        ),
    ]
